//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETicaretEntities : DbContext
    {
        public ETicaretEntities()
            : base("name=ETicaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_fatura> tbl_fatura { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_kategori> tbl_kategori { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
        public virtual DbSet<tbl_marka> tbl_marka { get; set; }
        public virtual DbSet<tbl_model> tbl_model { get; set; }
        public virtual DbSet<tbl_rol> tbl_rol { get; set; }
        public virtual DbSet<tbl_sepet> tbl_sepet { get; set; }
        public virtual DbSet<tbl_sepetDetay> tbl_sepetDetay { get; set; }
        public virtual DbSet<tbl_siparis> tbl_siparis { get; set; }
        public virtual DbSet<tbl_siparisDetay> tbl_siparisDetay { get; set; }
        public virtual DbSet<tbl_siparisDurum> tbl_siparisDurum { get; set; }
        public virtual DbSet<tbl_tedarikci> tbl_tedarikci { get; set; }
        public virtual DbSet<tbl_tedarikSiparisDetay> tbl_tedarikSiparisDetay { get; set; }
        public virtual DbSet<tbl_tedarikSiparisleri> tbl_tedarikSiparisleri { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
    }
}
