//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sepetDetay
    {
        public int sepetDetay_ID { get; set; }
        public int sepet_ID { get; set; }
        public int urun_ID { get; set; }
        public byte adet { get; set; }
        public decimal birim_fiyat { get; set; }
        public decimal toplam_fiyat { get; set; }
    
        public virtual tbl_sepet tbl_sepet { get; set; }
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
