//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tedarikci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tedarikci()
        {
            this.tbl_tedarikSiparisleri = new HashSet<tbl_tedarikSiparisleri>();
        }
    
        public int tedarikci_ID { get; set; }
        public string tedarikci_adi { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tedarikSiparisleri> tbl_tedarikSiparisleri { get; set; }
    }
}
