//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tedarikSiparisDetay
    {
        public int tedarikSiparisDetay_ID { get; set; }
        public int tedarikSiparis_ID { get; set; }
        public int urun_ID { get; set; }
        public byte adet { get; set; }
        public decimal birim_maliyet { get; set; }
        public decimal toplam_maliyet { get; set; }
    
        public virtual tbl_tedarikSiparisleri tbl_tedarikSiparisleri { get; set; }
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
