//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatura
    {
        public int fatura_ID { get; set; }
        public int siparis_ID { get; set; }
        public decimal toplam_tutar { get; set; }
        public System.DateTime fatura_tarihi { get; set; }
    
        public virtual tbl_siparis tbl_siparis { get; set; }
    }
}
