//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kullanici()
        {
            this.tbl_iletisim = new HashSet<tbl_iletisim>();
            this.tbl_sepet = new HashSet<tbl_sepet>();
            this.tbl_siparis = new HashSet<tbl_siparis>();
        }
    
        public int kullanici_ID { get; set; }
        public int rol_ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telefon_no { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
        public string sifre { get; set; }
        public System.DateTime kayit_tarihi { get; set; }
        public string reset_token_hash { get; set; }
        public Nullable<System.DateTime> reset_token_sona_erme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual tbl_rol tbl_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sepet> tbl_sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_siparis> tbl_siparis { get; set; }
    }
}
