//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_siparis()
        {
            this.tbl_fatura = new HashSet<tbl_fatura>();
            this.tbl_siparisDetay = new HashSet<tbl_siparisDetay>();
        }
    
        public int siparis_ID { get; set; }
        public int kullanici_ID { get; set; }
        public int siparisDurum_ID { get; set; }
        public decimal toplam_tutar { get; set; }
        public string teslimat_adresi { get; set; }
        public System.DateTime siparis_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_fatura> tbl_fatura { get; set; }
        public virtual tbl_kullanici tbl_kullanici { get; set; }
        public virtual tbl_siparisDurum tbl_siparisDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_siparisDetay> tbl_siparisDetay { get; set; }
    }
}
