//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tedarikSiparisleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tedarikSiparisleri()
        {
            this.tbl_tedarikSiparisDetay = new HashSet<tbl_tedarikSiparisDetay>();
        }
    
        public int tedarikSiparis_ID { get; set; }
        public int tedarikci_ID { get; set; }
        public decimal toplam_tutar { get; set; }
        public System.DateTime siparis_tarihi { get; set; }
    
        public virtual tbl_tedarikci tbl_tedarikci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tedarikSiparisDetay> tbl_tedarikSiparisDetay { get; set; }
    }
}
