//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_iletisim
    {
        public int iletisim_ID { get; set; }
        public int kullanici_ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public string mesaj { get; set; }
        public System.DateTime gonderim_tarihi { get; set; }
    
        public virtual tbl_kullanici tbl_kullanici { get; set; }
    }
}
