//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazEsyaE_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_urun()
        {
            this.tbl_sepetDetay = new HashSet<tbl_sepetDetay>();
            this.tbl_siparisDetay = new HashSet<tbl_siparisDetay>();
            this.tbl_tedarikSiparisDetay = new HashSet<tbl_tedarikSiparisDetay>();
        }
    
        public int urun_ID { get; set; }
        public int kategori_ID { get; set; }
        public int marka_ID { get; set; }
        public int model_ID { get; set; }
        public string urun_adi { get; set; }
        public string aciklama { get; set; }
        public byte mevcut_stok { get; set; }
        public decimal fiyat { get; set; }
        public string gorsel { get; set; }
        public bool oneCikan_mi { get; set; }
        public bool aktif_mi { get; set; }
    
        public virtual tbl_kategori tbl_kategori { get; set; }
        public virtual tbl_marka tbl_marka { get; set; }
        public virtual tbl_model tbl_model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sepetDetay> tbl_sepetDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_siparisDetay> tbl_siparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tedarikSiparisDetay> tbl_tedarikSiparisDetay { get; set; }
    }
}
